### ISSUE TITLE
exception when clicking on the map

### ISSUE THREAD

**Issue by yaelAmitay** [TechnionYP5777/SmartCity-Accessibility#176]
I'm not sure if it's just me or not but when i'm clicking on the map the following exception is thrown:
`Exception in thread "pool-1-thread-1" java.lang.NullPointerException
	at smartcity.accessibility.database.LocationManager$3.done(LocationManager.java:135)
	at org.parse4j.ParseQuery$FindInBackgroundThread.run(ParseQuery.java:623)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by kapalex** [comment]
This seems new
On click the GUI calls the `getLocation` function, so @assaflu  should be able to help with it

**Comment by yaelAmitay** [comment]
@assaflu  told me he changes getLocation, and now you should call the new function with callback function

**Comment by yaelAmitay** [comment]
@KaplanAlexander

**Comment by kapalex** [comment]
Will change asap

**Comment by kapalex** [comment]
I updated it to use the new getLocation
exception are still thrown when calling both location and review update, @assaflu check it out
