### ISSUE TITLE
Runtime error when trying to upvote new review

### ISSUE THREAD

**Issue by kapalex** [TechnionYP5777/SmartCity-Accessibility#397]
When adding a new review to a location, then trying to upvote it the following error is thrown
```
Runtime Error
Error in ./GetReviewsPage class GetReviewsPage - caused by: Cannot read property 'coordinates' of null

Stack
TypeError: Cannot read property 'coordinates' of null
    at GetReviewsService.changeRevLikes (http://localhost/build/main.js:84524:43)
    at GetReviewsPage.like (http://localhost/build/main.js:84600:26)
    at View_GetReviewsPage2.handleEvent_20 (/AppModule/GetReviewsPage/component.ngfactory.js:452:45)
    at View_GetReviewsPage2.<anonymous> (http://localhost/build/main.js:113916:37)
    at HTMLButtonElement.<anonymous> (http://localhost/build/main.js:56493:53)
    at t.invokeTask (http://localhost/build/polyfills.js:3:10284)
    at Object.onInvokeTask (http://localhost/build/main.js:36939:37)
    at t.invokeTask (http://localhost/build/polyfills.js:3:10220)
    at e.runTask (http://localhost/build/polyfills.js:3:7637)
    at HTMLButtonElement.invoke (http://localhost/build/polyfills.js:3:11397)
```

**Comment by kapalex** [comment]
@ArthurSap  if this isn't your assign whoever is in charge

**Comment by ArthurSap** [comment]
@Kolikant I need you on this one,
when you click to view a location's reviews currently you're passing just the LatLng, I need you to pass the location's type, sub-type and name as well.

**Comment by Kolikant** [comment]
Im currently passing them since that is all tour function took, will add the new paramaters soon, just make sure to write them all in the method signature

**Comment by ArthurSap** [comment]
Using it as "type", "subtype" and "name" in the constructor

**Comment by ArthurSap** [comment]
Doesn't crash anymore but for some reason the spinner isn't showing, the liking/disliking doesn't affect the review on the server side (update isn't saved) and the review's location attribute is null

**Comment by kapalex** [comment]
You need to update the review through the ReviewManager and not the LocationManager
Also you need to check if the current user is already in the comment list for said review, and if he is he cannot comment again

**Comment by kapalex** [comment]
Actually correction, the comment system in the reviews already covers double reviews
but after you upvote\downvote you should simple use `getUpvotes` and `getDownvotes` to update the gui, because if the user upvotes twice the number won't change

**Comment by ArthurSap** [comment]
Eh, can we close it?
